name: Runner

targets:
  Runner:
    type: application
    platform: iOS

    preBuildScripts:
      - name: Build
        path: "/bin/sh"
        script: |
          "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build

    sources:
      - path: Runner/AppDelegate.swift
        buildPhase: sources
      - path: Runner/GeneratedPluginRegistrant.m
        buildPhase: sources

      - path: Flutter/AppFrameworkInfo.plist
        buildPhase: resources
      - path: Runner/Assets.xcassets
        buildPhase: resources
      - path: Runner/Base.lproj/LaunchScreen.storyboard
        buildPhase: resources
      - path: Runner/Base.lproj/Main.storyboard
        buildPhase: resources

    postBuildScripts:
      - name: Thin Binary
        inputFiles:
          - ${TARGET_BUILD_DIR}/${INFOPLIST_PATH}
        path: "/bin/sh"
        script: |
          "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed_and_thin

    settings:
      base:
        PRODUCT_NAME: Ddns4cdn
        PRODUCT_BUNDLE_IDENTIFIER: best.jat.ddns4cdn
        PRODUCT_COPYRIGHT: Copyright © 2023 Jat. All rights reserved.
        DEVELOPMENT_TEAM: H2SHN33HHY

        INFOPLIST_FILE: Runner/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: Runner/Runner-Bridging-Header.h
      configs:
        Debug:
        Release:
    configFiles:
      Debug: Runner/Configs/Debug.xcconfig
      Release: Runner/Configs/Release.xcconfig
