name: ddns4cdn
description: Automatically update the IP address of origin server for CDN.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  path: ^1.8.3
  path_provider: ^2.1.1
  desktop_webview_window: ^0.2.3
  shelf: ^1.4.1

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
